// Generated by CoffeeScript 1.12.7
(function() {
  'use strict';
  var breadcrumbsGetParticipationDefer, makeRegExp;

  breadcrumbsGetParticipationDefer = void 0;

  makeRegExp = function($scope, type_site) {
    var exemples, patt;
    patt = {
      'CARRE': /^Cir.+-\d{4}-Pass\d{1,2}-Tron\d{1,2}-Chiro_([01]_)?\d+_\d{3}\.(wav|ta|tac)(.zip)?$/,
      'POINT_FIXE': /^Car.+-\d{4}-Pass\d{1,2}-([A-H][12]|Z[1-9][0-9]*)-.*_\d{8}_\d{6}_\d{3}\.(wav|ta|tac)(.zip)?$/,
      'ROUTIER': /^Cir.+-\d{4}-Pass\d{1,2}-Tron\d{1,2}-Chiro_([01]_)?\d+_\d{3}\.(wav|ta|tac)(.zip)?$/
    };
    exemples = {
      'CARRE': 'Cir270-2009-Pass1-Tron1-Chiro_0_00265_000.wav, batch-01.wav.zip',
      'POINT_FIXE': 'Car170517-2014-Pass1-C1-OB-1_20140702_224038_761.wav, batch-01.wav.zip',
      'ROUTIER': 'Cir270-2009-Pass1-Tron1-Chiro_0_00265_000.wav, batch-01.wav.zip'
    };
    $scope.regexp = patt[type_site];
    return $scope.fileFormatExemple = exemples[type_site];
  };

  angular.module('uploadParticipationViews', ['ngRoute', 'xin_listResource', 'xin_backend', 'xin_session', 'xin_tools', 'xin_uploadFile']).config(function($routeProvider) {
    return $routeProvider.when('/participations/:participationId/telechargement', {
      templateUrl: 'scripts/views/participation_upload/upload.html',
      controller: 'AddParticipationFilesController',
      breadcrumbs: ngInject(function($q, $filter) {
        var breadcrumbsDefer;
        breadcrumbsDefer = $q.defer();
        breadcrumbsGetParticipationDefer = $q.defer();
        breadcrumbsGetParticipationDefer.promise.then(function(participation) {
          return breadcrumbsDefer.resolve([['Participations', '#/participations'], ['Participation du ' + $filter('date')(participation.date_debut, 'medium'), '#/participations/' + participation._id], ['Téléchargement', '#/participations/' + participation._id + '/edition']]);
        });
        return breadcrumbsDefer.promise;
      })
    });
  }).controller('AddParticipationFilesController', function($scope, $routeParams, Backend, session) {
    var participationResource;
    participationResource = null;
    $scope.participation = null;
    $scope.participationId = $routeParams.participationId;
    Backend.one("participations", $routeParams.participationId).get().then(function(participation) {
      $scope.participationWaiting = false;
      if (breadcrumbsGetParticipationDefer != null) {
        breadcrumbsGetParticipationDefer.resolve(participation);
        breadcrumbsGetParticipationDefer = void 0;
      }
      participationResource = participation;
      $scope.participation = participation.plain();
      return makeRegExp($scope, participation.protocole.type_site);
    }, function(error) {
      return window.location = "#/404";
    });
    $scope.computeDone = {};
    return $scope.compute = function() {
      $scope.computeInfo = {};
      return participationResource.post('compute', {}).then(function(result) {
        return window.location = "#/participations/" + participationResource._id;
      }, function(error) {
        var base;
        $scope.computeInfo.error = true;
        return typeof (base = $scope.computeDone).end === "function" ? base.end() : void 0;
      });
    };
  });
  //ajout a reprendre
 /* $scope.infoUpload = function() {
          var modalInstance;
          modalInstance = $modal.open({
            templateUrl: 'scripts/views/xin/upload_file/info_upload.html',
            controller: 'ModalInstanceController',
          });
        }; */ 
  //fin de l'ajout
}).call(this);
