// Generated by CoffeeScript 1.12.7
(function() {
  'use strict';

  /**
    * @ngdoc function
    * @name xin.controller:LoginCtrl
    * @description
    * # LoginCtrl
    * Controller of the xin
   */
  angular.module('xin_login', ['ngRoute', 'xin_session', 'appSettings']).directive('loginDirective', function($location, $rootScope, $route, session, SETTINGS) {
    return {
      restrict: 'E',
      templateUrl: 'scripts/xin/login_drt/login.html',
      link: function($scope, elem, attrs) {
        var content_elem, detectLoginNeeded, login_elem, routeParams, token;
        routeParams = $route.current.params;
        if (routeParams.token != null) {
          token = routeParams.token;
          $location.search('token', null).replace();
          session.login(token);
        }
        $scope.api_domain = SETTINGS.API_DOMAIN;
        login_elem = elem;
        content_elem = $('content-directive');
        detectLoginNeeded = function(currentRoute) {
          if (currentRoute.no_login != null) {
            content_elem.show();
            return login_elem.hide();
          } else {
            return session.getUserPromise().then(function() {
              content_elem.show();
              return login_elem.hide();
            }, function() {
              content_elem.hide();
              return login_elem.show();
            });
          }
        };
        $rootScope.$on('$routeChangeSuccess', function(currentRoute, previousRoute) {
          detectLoginNeeded($route.current.$$route);
        });
        return detectLoginNeeded($route.current.$$route);
      }
    };
  });

}).call(this);
