// Generated by CoffeeScript 1.12.7
(function() {
  'use strict';
  angular.module('modalParticipationViews', []).controller('ModalDeleteParticipationController', function($scope, $modalInstance) {
    $scope.ok = function() {
      return $modalInstance.close(true);
    };
    return $scope.cancel = function() {
      return $modalInstance.dismiss('cancel');
    };
  });

}).call(this);
