// Generated by CoffeeScript 1.12.7
(function() {
  'use strict';
  angular.module('sc-button', []).directive('scButton', function() {
    return {
      restrict: 'E',
      template: "<span class=\"{{labelClass}}\" ng-show=\"labelClass\">&nbsp;&nbsp;</span>{{label}} <span class=\"{{waitClass}}\"></span>",
      scope: {
        waitForClass: "@?",
        cancelWaitFor: "=?",
        label: "=?",
        labelClass: "=?"
      },
      link: function(scope, elem, attrs) {
        scope.waitClass = "";
        elem[0].addEventListener('click', function(e) {
          elem[0].setAttribute("disabled", "");
          return scope.waitClass = scope.waitForClass;
        });
        if (scope.cancelWaitFor != null) {
          return scope.cancelWaitFor.end = function() {
            elem[0].removeAttribute("disabled");
            return scope.waitClass = "";
          };
        }
      }
    };
  });

}).call(this);
