// Generated by CoffeeScript 1.12.7
(function() {
  'use strict';
  var breadcrumbsGetUtilisateurDefer;

  breadcrumbsGetUtilisateurDefer = void 0;


  /**
    * @ngdoc function
    * @name vigiechiroApp.controller:ShowUtilisateurCtrl
    * @description
    * # ShowUtilisateurCtrl
    * Controller of the vigiechiroApp
   */

  angular.module('utilisateurViews', ['ngRoute', 'xin_listResource', 'xin_tools', 'xin_session', 'xin_backend']).config(function($routeProvider) {
    return $routeProvider.when('/utilisateurs', {
      templateUrl: 'scripts/views/utilisateur/list_utilisateurs.html',
      controller: 'ListUtilisateursController',
      breadcrumbs: 'Utilisateurs'
    }).when('/utilisateurs/:userId', {
      templateUrl: 'scripts/views/utilisateur/show_utilisateur.html',
      controller: 'ShowUtilisateurController',
      breadcrumbs: ngInject(function($q) {
        var breadcrumbsDefer;
        breadcrumbsDefer = $q.defer();
        breadcrumbsGetUtilisateurDefer = $q.defer();
        breadcrumbsGetUtilisateurDefer.promise.then(function(utilisateur) {
          return breadcrumbsDefer.resolve([['Utilisateurs', '#/utilisateurs'], [utilisateur.pseudo, '#/utilisateurs/' + utilisateur._id]]);
        });
        return breadcrumbsDefer.promise;
      })
    });
  }).controller('ListUtilisateursController', function($scope, Backend, DelayedEvent) {
    var delayedFilter;
    $scope.lookup = {};
    delayedFilter = new DelayedEvent(500);
    $scope.filterField = '';
    $scope.$watch('filterField', function(filterValue) {
      return delayedFilter.triggerEvent(function() {
        if ((filterValue != null) && filterValue !== '') {
          return $scope.lookup.q = filterValue;
        } else if ($scope.lookup.q != null) {
          return delete $scope.lookup.q;
        }
      });
    });
    return $scope.resourceBackend = Backend.all('utilisateurs');
  }).controller('ShowUtilisateurController', function($scope, $route, $routeParams, Backend, session) {
    var origin_donnees_publiques, origin_professionnel, origin_role, userBackend, userResource;
    $scope.submitted = false;
    $scope.utilisateur = {};
    $scope.readOnly = false;
    $scope.isSelf = false;
    $scope.isAdmin = false;
    $scope.displayCharte = function() {
      return $('#charteModal').modal();
    };
    userResource = void 0;
    origin_role = void 0;
    origin_professionnel = void 0;
    origin_donnees_publiques = void 0;
    userBackend = void 0;
    if ($routeParams.userId === 'moi') {
      userBackend = Backend.one('moi');
    } else {
      userBackend = Backend.one('utilisateurs', $routeParams.userId);
    }
    userBackend.get().then(function(utilisateur) {
      if (breadcrumbsGetUtilisateurDefer != null) {
        breadcrumbsGetUtilisateurDefer.resolve(utilisateur);
        breadcrumbsGetUtilisateurDefer = void 0;
      }
      userResource = utilisateur;
      $scope.utilisateur = utilisateur.plain();
      origin_role = $scope.utilisateur.role;
      origin_professionnel = $scope.utilisateur.professionnel;
      origin_donnees_publiques = $scope.utilisateur.donnees_publiques;
      return session.getUserPromise().then(function(user) {
        $scope.isSelf = user._id === utilisateur._id;
        $scope.isAdmin = user.role === 'Administrateur';
        return $scope.readOnly = !$scope.isAdmin && !$scope.isSelf;
      });
    }, function(error) {
      return window.location = '#/404';
    });
    $scope.resetCharteAccept = function() {
      if ($routeParams.userId === 'moi') {
        return session.getUserPromise().then(function(user) {
          return Backend.one('utilisateurs', user._id).one('reset_charte').post().then(function() {
            return $route.reload();
          }, function(error) {
            return $scope.saveError = true;
          });
        });
      } else {
        return Backend.one('utilisateurs', $routeParams.userId).one('reset_charte').post().then(function() {
          return $route.reload();
        }, function(error) {
          return $scope.saveError = true;
        });
      }
    };
    return $scope.saveUser = function() {
      var key, payload, ref, value;
      $scope.submitted = true;
      if (!$scope.userForm.$valid || !$scope.userForm.$dirty || (userResource == null)) {
        return;
      }
      payload = {};
      ref = $scope.userForm;
      for (key in ref) {
        value = ref[key];
        if (key.charAt(0) !== '$' && value.$dirty) {
          payload[key] = $scope.utilisateur[key];
        }
      }
      if ($scope.utilisateur.role !== origin_role) {
        payload.role = $scope.utilisateur.role;
      }
      if ($scope.utilisateur.professionnel !== origin_professionnel) {
        payload.professionnel = $scope.utilisateur.professionnel;
      }
      if ($scope.utilisateur.donnees_publiques !== origin_donnees_publiques) {
        payload.donnees_publiques = $scope.utilisateur.donnees_publiques;
      }
      return userBackend.patch(payload).then(function() {
        return $route.reload();
      }, function(error) {
        return $scope.saveError = true;
      });
    };
  });

}).call(this);
