// Generated by CoffeeScript 1.12.7
(function() {
  'use strict';
  angular.module('xin_storage', []).factory('storage', function() {
    var Storage;
    return Storage = (function() {
      function Storage() {}

      Storage.getItem = function(key) {
        return window.localStorage.getItem(key);
      };

      Storage.setItem = function(key, value) {
        return window.localStorage.setItem(key, value);
      };

      Storage.removeItem = function(key) {
        return window.localStorage.removeItem(key);
      };

      Storage.clear = function() {
        return window.localStorage.clear();
      };

      Storage.addEventListener = function(handler) {
        if (window.addEventListener != null) {
          return window.addEventListener("storage", handler, false);
        } else {
          return window.attachEvent("onstorage", handler);
        }
      };

      return Storage;

    })();
  });

}).call(this);
