// Generated by CoffeeScript 1.12.7
(function() {
  'use strict';
  angular.module('appSettings', []).constant('SETTINGS', {
    API_DOMAIN: 'http://localhost:8080',
    FRONT_DOMAIN: 'http://localhost:9000',
    BASE_TITLE: 'Vigiechiro'
  });

}).call(this);
