name: Upload files to WebDAV

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
          WEBDAV_USERNAME: "${{secrets.WEBDAV_USERNAME}}"
          WEBDAV_PASSWORD: "${{secrets.WEBDAV_PASSWORD}}"
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Cyberduck CLI
        run: |
          sudo apt update
          sudo apt install yum
          echo -e "[duck-stable]\nname=duck-stable\nbaseurl=https://repo.cyberduck.io/stable/\$basearch/\nenabled=1\ngpgcheck=0" | sudo tee /etc/yum.repos.d/duck-stable.repo
          sudo yum install duck

      - name: Upload files
        run: |
          echo "WebDAV username: $WEBDAV_USERNAME"
          echo "WebDAV password: $WEBDAV_PASSWORD"
          echo "Uploading app directory to server"
          duck --upload protocol:/$WEBDAV_USERNAME:$WEBDAV_PASSWORD@vigiechiro-dev.in2p3.fr/_webdav_/app/ C:/Users/bbees/Documents/GitHub/vigiechiro-front-test-cc/app/
          echo "Upload complete"