name: Upload files to WebDAV

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
          WEBDAV_USERNAME: ${{ secrets.WEBDAV_USERNAME }}
          WEBDAV_PASSWORD: ${{ secrets.WEBDAV_PASSWORD }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Cyberduck CLI
        run: |
          choco install duck -y

      - name: Upload files
        run: |
          duck --username ${{ secrets.WEBDAV_USERNAME }} --password ${{ secrets.WEBDAV_PASSWORD }} \
          -q put ./app/ https://vigiechiro-dev.in2p3.fr/_webdav/app

        
