name: Upload files to WebDAV

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
          WEBDAV_USERNAME: "${{secrets.WEBDAV_USERNAME}}"
          WEBDAV_PASSWORD: "${{secrets.WEBDAV_PASSWORD}}"
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Cyberduck CLI
        run: |
          sudo apt-get update
          sudo apt-get upgrade
          sudo apt-get install duck -y

      - name: Upload files
        run: |
          echo "WebDAV username: $WEBDAV_USERNAME"
          echo "WebDAV password: $WEBDAV_PASSWORD"
          echo "Uploading app directory to server"
          duck upload -r C:/Users/bbees/Documents/GitHub/vigiechiro-front-test-cc/app remote://$WEBDAV_USERNAME:$WEBDAV_PASSWORD@vigiechiro-dev.in2p3.fr/_webdav_/app/
          echo "Upload complete"