// Generated by CoffeeScript 1.12.7
(function() {
  "user strict";
  angular.module('xin_content', ['xin_session']).directive('contentDirective', function(session) {
    return {
      restrict: 'E'
    };
  });

}).call(this);
